version: '3.7'

services:
    db:
        image: mysql:5.7.22
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./mysql/data:/var/lib/mysql
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            #        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $${MYSQL_USER} --password=$${MYSQL_PASSWORD}

    php:
        build: ./php
        ports:
        - "9000:9000"        
        volumes:
            - ./app/html:/var/www/html
            - ./app/pae:/var/www/pae
            - ./app/files:/var/www/pae/sites/default/files
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            DRUPAL_ADMIN_USER: ${DRUPAL_ADMIN_USER}
            DRUPAL_ADMIN_PASSWORD: ${DRUPAL_ADMIN_PASSWORD}
            DRUPAL_ADMIN_EMAIL: ${DRUPAL_ADMIN_EMAIL}  
            DRUPAL_SITE_NAME: ${DRUPAL_SITE_NAME}   
        depends_on:
            - db
    web:
        image: nginx:stable
        ports:
        - "80:80"
        volumes:
#            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app/html:/var/www/html
            - ./app/pae:/var/www/pae
            - ./app/files:/var/www/pae/sites/default/files
        environment:
            - NGINX_HOST=pae.test
            - NGINX_PORT=80
            - TZ=UTC
        depends_on:
            - php
